// Getting .env file's constant values
const WEATHER_API_KEY = process.env.REACT_APP_WEATHER_API_KEY;
const DEFAULT_EXPIRE_TIME = 5;
const SECONDS = 60;
const MILLISECONDS = 1000;

export { WEATHER_API_KEY, DEFAULT_EXPIRE_TIME, SECONDS, MILLISECONDS };
